In [2]:
from sklearn import svm
from sklearn import datasets

# Understand iris dataset first (In copy)

In [5]:
iris = datasets.load_iris()

In [13]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [24]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#    ## 0 = iris-setosa            1 = iris-valentina           2 = iris-verosa

In [26]:
#Now dividing the X dataset and Y dataset
X = iris.data[:,2]  #Using column 2 (that is sepal width) to determine the species of flower,   several X value could be given
y = iris.target

In [34]:
from sklearn.model_selection import train_test_split

In [36]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

In [67]:
# modified is done to convert into 1d hokiii 2d, else jupyter wont be able to do operation 
x_train_modified = x_train.reshape(-1,1)
x_test_modified = x_test.reshape(-1,1)
y_train_modified = y_train.reshape(-1,1)
y_test_modified = y_test.reshape(-1,1)
#you can also do ravel

# SVM (Support Vector Method)

In [68]:
model_svm = svm.SVC()

In [42]:
model_svm.fit(x_train_modified,y_train_modified)       #this is training the data(x and y) using SVM model

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [45]:
#Now here the dataset is trained, Now we have to get the value from Algorithm, and test it with our original value
y_predict = model_svm.predict(x_test_modified)

In [46]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [49]:
print(accuracy_score(y_test_modified, y_predict))      #measuring accuracy

0.9333333333333333


In [53]:
print(confusion_matrix(y_test_modified, y_predict))

[[10  0  0]
 [ 0 12  1]
 [ 0  1  6]]


In [54]:
print(classification_report(y_test_modified, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.92      0.92      0.92        13
           2       0.86      0.86      0.86         7

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



# KNN(K Nearest Neighbors)

In [56]:
from sklearn.neighbors import KNeighborsClassifier

In [60]:
model_knn = KNeighborsClassifier(n_neighbors=1)

In [62]:
model_knn.fit(x_train_modified, y_train_modified)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [65]:
# TO GET ANSWER FROM ALGORIHM USING TEST DATASET
y_prediction_knn = model_knn.predict(x_test_modified)

In [70]:
# TO GET ACCURACY
print(accuracy_score(y_test_modified,y_prediction_knn))

#print(classification_report(y_test_modified,y_prediction_knn))
#print(confusion_matrix(y_test_modified,y_prediction_knn))

0.9333333333333333


# Logistic Regression

In [72]:
from sklearn.linear_model import LogisticRegression

In [77]:
model_logi_regres = LogisticRegression()

In [79]:
model_logi_regres.fit(x_train_modified, y_train_modified)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [81]:
y_predict_logiRegression = model_logi_regres.predict(x_test_modified)

In [83]:
# TO TEST ACCURACY
print(accuracy_score(y_test_modified, y_predict_logiRegression))

0.6


In [85]:
#THIS IS JUST PRACTICE

In [86]:
x_train_modified

array([[4.6],
       [4.3],
       [5.8],
       [5.1],
       [5. ],
       [1.4],
       [5.7],
       [5.7],
       [6.9],
       [5.1],
       [1.6],
       [1.6],
       [3.9],
       [1.3],
       [4.7],
       [1.5],
       [4.9],
       [4.8],
       [4.9],
       [5.7],
       [4.5],
       [6.1],
       [3.7],
       [4.5],
       [4.5],
       [1.2],
       [1.5],
       [4.7],
       [1.7],
       [5.5],
       [1.6],
       [1.5],
       [4.5],
       [3. ],
       [5.6],
       [1.4],
       [5.4],
       [1.4],
       [3.9],
       [5.1],
       [1.3],
       [5.9],
       [6.4],
       [5.5],
       [6.6],
       [5.1],
       [1.4],
       [3.5],
       [5.8],
       [4.1],
       [1.5],
       [5.6],
       [4.7],
       [4.2],
       [1.4],
       [1.7],
       [1.9],
       [4.5],
       [6.1],
       [5.6],
       [4.4],
       [1.5],
       [1.6],
       [1.4],
       [5.8],
       [5.1],
       [4. ],
       [3.8],
       [5.1],
       [5.2],
       [5.1],
      